name: rate_trip
description: A new Flutter package project.
version: 0.0.1
homepage: null

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.3.1
  image_picker: ^0.8.4+11
  mocktail: ^0.3.0
  provider: ^6.0.2
  sliding_up_panel: ^2.0.0+1

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/
    - .env
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Gordita-Medium
      fonts:
        - asset: assets/fonts/gordita/Gordita-Medium.otf
    - family: Gordita-Bold
      fonts:
        - asset: assets/fonts/gordita/Gordita-Bold.otf
    - family: Gordita
      fonts:
        - asset: assets/fonts/gordita/Gordita-Bold.otf
        - asset: assets/fonts/gordita/Gordita-Medium.otf
        - asset: assets/fonts/gordita/Gordita-Regular.otf
        - asset: assets/fonts/gordita/Gordita-Regular-Italic.otf
          style: italic
